version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mariadb:latest 
    container_name: wordpress_db
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
